# Generated by Django 3.1.7 on 2021-08-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210815_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='msg',
        ),
    ]
